/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookACallRouteImport } from './routes/book-a-call'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWebSystemsRouteImport } from './routes/services.web-systems'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesDataPipelinesRouteImport } from './routes/services.data-pipelines'
import { Route as ServicesAutomationRouteImport } from './routes/services.automation'
import { Route as ServicesAiIntegrationsRouteImport } from './routes/services.ai-integrations'
import { Route as ServicesAiAgentsRouteImport } from './routes/services.ai-agents'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookACallRoute = BookACallRouteImport.update({
  id: '/book-a-call',
  path: '/book-a-call',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebSystemsRoute = ServicesWebSystemsRouteImport.update({
  id: '/services/web-systems',
  path: '/services/web-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDataPipelinesRoute = ServicesDataPipelinesRouteImport.update({
  id: '/services/data-pipelines',
  path: '/services/data-pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAutomationRoute = ServicesAutomationRouteImport.update({
  id: '/services/automation',
  path: '/services/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiIntegrationsRoute = ServicesAiIntegrationsRouteImport.update({
  id: '/services/ai-integrations',
  path: '/services/ai-integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAgentsRoute = ServicesAiAgentsRouteImport.update({
  id: '/services/ai-agents',
  path: '/services/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-a-call': typeof BookACallRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-integrations': typeof ServicesAiIntegrationsRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/data-pipelines': typeof ServicesDataPipelinesRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-systems': typeof ServicesWebSystemsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-a-call': typeof BookACallRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-integrations': typeof ServicesAiIntegrationsRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/data-pipelines': typeof ServicesDataPipelinesRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-systems': typeof ServicesWebSystemsRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-a-call': typeof BookACallRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-agents': typeof ServicesAiAgentsRoute
  '/services/ai-integrations': typeof ServicesAiIntegrationsRoute
  '/services/automation': typeof ServicesAutomationRoute
  '/services/data-pipelines': typeof ServicesDataPipelinesRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/web-systems': typeof ServicesWebSystemsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book-a-call'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/services/ai-agents'
    | '/services/ai-integrations'
    | '/services/automation'
    | '/services/data-pipelines'
    | '/services/seo'
    | '/services/web-systems'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book-a-call'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/services/ai-agents'
    | '/services/ai-integrations'
    | '/services/automation'
    | '/services/data-pipelines'
    | '/services/seo'
    | '/services/web-systems'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/book-a-call'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/services/ai-agents'
    | '/services/ai-integrations'
    | '/services/automation'
    | '/services/data-pipelines'
    | '/services/seo'
    | '/services/web-systems'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookACallRoute: typeof BookACallRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ServicesAiAgentsRoute: typeof ServicesAiAgentsRoute
  ServicesAiIntegrationsRoute: typeof ServicesAiIntegrationsRoute
  ServicesAutomationRoute: typeof ServicesAutomationRoute
  ServicesDataPipelinesRoute: typeof ServicesDataPipelinesRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebSystemsRoute: typeof ServicesWebSystemsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-call': {
      id: '/book-a-call'
      path: '/book-a-call'
      fullPath: '/book-a-call'
      preLoaderRoute: typeof BookACallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-systems': {
      id: '/services/web-systems'
      path: '/services/web-systems'
      fullPath: '/services/web-systems'
      preLoaderRoute: typeof ServicesWebSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/data-pipelines': {
      id: '/services/data-pipelines'
      path: '/services/data-pipelines'
      fullPath: '/services/data-pipelines'
      preLoaderRoute: typeof ServicesDataPipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automation': {
      id: '/services/automation'
      path: '/services/automation'
      fullPath: '/services/automation'
      preLoaderRoute: typeof ServicesAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-integrations': {
      id: '/services/ai-integrations'
      path: '/services/ai-integrations'
      fullPath: '/services/ai-integrations'
      preLoaderRoute: typeof ServicesAiIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-agents': {
      id: '/services/ai-agents'
      path: '/services/ai-agents'
      fullPath: '/services/ai-agents'
      preLoaderRoute: typeof ServicesAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BookACallRoute: BookACallRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ServicesAiAgentsRoute: ServicesAiAgentsRoute,
  ServicesAiIntegrationsRoute: ServicesAiIntegrationsRoute,
  ServicesAutomationRoute: ServicesAutomationRoute,
  ServicesDataPipelinesRoute: ServicesDataPipelinesRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebSystemsRoute: ServicesWebSystemsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
